// Copyright 2020 Christopher Courtney, aka Drashna Jael're  (@drashna) <drashna@live.com>
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once
#define NO_MUSIC_MODE

// #include "features/audio_song_list.h"

// #ifdef USER_SONG_LIST
// #    define STARTUP_SONG SONG(RICK_ROLL)
// #    define GOODBYE_SONG SONG(SONIC_RING)
// #    define DEFAULT_LAYER_SONGS { SONG(QWERTY_SOUND), SONG(COLEMAK_SOUND), SONG(DVORAK_SOUND), SONG(OVERWATCH_THEME) }
// #    define UNICODE_SONG_MAC SONG(MARIO_THEME)
// #    define UNICODE_SONG_LNX SONG(MARIO_POWERUP)
// #    define UNICODE_SONG_WIN SONG(MARIO_ONEUP)
// #    define UNICODE_SONG_BSD SONG(RICK_ROLL)
// #    define UNICODE_SONG_WINC SONG(RICK_ROLL)
// #endif
#undef STARTUP_SONG
// #define STARTUP_SONG SONG(STARTUP_SOUND)
#define STARTUP_SONG SONG(ZELDA_PUZZLE_2)
#undef GOODBYE_SONG
#define GOODBYE_SONG SONG(BYE_SOUND)
#undef DEFAULT_LAYER_SONGS
#define DEFAULT_LAYER_SONGS \
    { SONG(QWERTY_SOUND), SONG(COLEMAK_SOUND) }
#define UNICODE_SONG_MAC SONG(QWERTY_SOUND)
#define UNICODE_SONG_LNX SONG(COLEMAK_SOUND)
#define UNICODE_SONG_WIN SONG(DVORAK_SOUND)
#define UNICODE_SONG_BSD SONG(WORKMAN_SOUND)
#define UNICODE_SONG_WINC SONG(PLOVER_GOODBYE_SOUND)
