#define CHARYBDIS_AUTO_SNIPING_ON_LAYER _POINTER
#define CHARYBDIS_MINIMUM_DEFAULT_DPI 600
#define CHARYBDIS_DEFAULT_DPI_CONFIG_STEP 200

#ifdef POINTING_DEVICE_ENABLE
// Automatically enable the pointer layer when moving the trackball.  See also:
// - `CHARYBDIS_AUTO_POINTER_LAYER_TRIGGER_TIMEOUT_MS`
// - `CHARYBDIS_AUTO_POINTER_LAYER_TRIGGER_THRESHOLD`
  #define CHARYBDIS_AUTO_POINTER_LAYER_TRIGGER_ENABLE
#endif // POINTING_DEVICE_ENABLE
